version: '3.7'

services:
    db:
        image: postgres:15.1-alpine
        container_name: postgres_sql
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: heimkapital
        ports:
            - "5432:5432"
        volumes:
            - type: bind
              source: ./data/postgres-init
              target: /docker-entrypoint-initdb.d
