version: '3.7'

services:
    db:
        image: postgres:15.1-alpine
        container_name: postgres_sql
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: heimkapital
        ports:
            - "5432:5432"
        volumes:
            - type: bind
              source: ./data/postgres-init
              target: /docker-entrypoint-initdb.d
    backend:
        image: sherjeelsikander/heimkapital:backend-v1
        container_name: heimkapital_backend
        ports:
            - "8080:8080"
    frontend:
        image: sherjeelsikander/heimkapital:frontend-v1
        container_name: heimkapital_frontend
        ports:
            - "80:80"
