version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "8005:8005"
    env_file:
      - server/.env
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=heimkapital
  client:
    build: ./client
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  postgres_data:
